server:
  port: 7070

spring:
  application:
    name: api-gateway

  cloud:
    config:
      enabled: false

    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/user/**
            - id : book-service
              uri: http://localhost:6060
              predicates:
                - Path=/api/book/**
#            - id: email-service
#              uri: http://localhost:5050
#              predicates:
#                - Path=/api/email/**

  main:
    web-application-type: reactive
