spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5423/bookdb
    username: user-service
    password: pass12
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
        hibernate:
          format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    servlet:
      path: /api/book
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
server:
  port: 6060
