spring:
  datasource:
    url: jdbc:postgresql://localhost:5423/userdb
    username: user-service
    password: pass12
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    servlet:
      path: /api/user
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password